### ISSUE TITLE
config opion all_episodes doesn't work, have to specify -A manually

### ISSUE THREAD

**Issue by Jacalz** [spaam/svtplay-dl#1009]
Getting this error when trying to download all episodes, even though the config has  `all_episodes: true `
```
jacalz@gitstallion ~ $ svtplay-dl https://www.svtplay.se/det-stora-kriget---svenska-oden
ERROR: No videos found. This mode is not supported anymore. Need the url with the video. 
```

Config:
 ```
default:
  path: ~/svtplay-dl/
  subtitle: true
  merge_subtitle: true
  all_episodes: true
  subfolder: true
  filename: "{title}.s{season}e{episode}.{episodename}.{ext}"
 ```
Usign -A solves the problem, but makes the config file kindof useless. Everything else from the config file works like it should...
