### ISSUE TITLE
Viafree.se - Won't use the config file to read login/password info

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1252]
### svtplay-dl versions:

svtplay-dl c5f777b

### Operating system and Python version:

Windows 10

### What is the issue:

To download from Viafree.se you need to login. I added my login info to the `svtplay-dl.yaml` file where i have all my other settings but it seems that it won't use it.

```
service:
  viafree:
    username: ********@gmail.com
    password: ***********
```

To get it to work i was forced to add it to the command line:
```
svtplay-dl.exe -S --force-subtitle -u ********@gmail.com -p *********** https://www.viafree.se/program/dokumentar/svenska-fall/sasong-5/avsnitt-1
INFO: Outfile: svenska.fall.s05e01.avsnitt.1-1042593-viaplay.srt
```

When trying to download the video it will at least show a message why it won't download the file
`ERROR: No videos found. You need to login`, but for some reason it won't use the config file.

**Comment by Sopor** [comment]
> https://github.com/spaam/svtplay-dl/issues/1251#issuecomment-692349377

I changed it to `viaplay` but i still get `INFO: No subtitles available` and if i try to download the video i get `ERROR: No videos found. You need to login`.

If i use -u and -p on the command line it works
```
svtplay-dl.exe -S --force-subtitle -u **********@gmail.com -p ********** https://www.viafree.se/program/dokumentar/svenska-fall/sasong-5/avsnitt-2
INFO: Outfile: svenska.fall.s05e02.avsnitt.2-1042787-viaplay.srt
```

**Comment by spaam** [comment]
did you put the config file in the correct place?

**Comment by spaam** [comment]
are you really sure you put the same username and password in both places?
do you have several `service` statements in the config file? 
it feels pretty strange it work for me and not you, sure i tried it on linux and macos. i dont have my windows machine on.

**Comment by Sopor** [comment]
After removing other services it will now work.

**Comment by spaam** [comment]
how did you have your file? 
A: 
```
service:
  viafree:
    username: ********@gmail.com
    password: ***********
  dplay:
    username: ********@gmail.com
    password: ***********
```
B: 
```
service:
  viafree:
    username: ********@gmail.com
    password: ***********
service:
  dplay:
    username: ********@gmail.com
    password: ***********
```
? 

it should be like A.
