### ISSUE TITLE
Subfolder config not working

### ISSUE THREAD

**Issue by GreveTess** [spaam/svtplay-dl#1397]
I just updated to the new 4.0 version and it doesn't seem to read the config file the same any more.
I weekly download children shows from SVTplay and today it stopped putting it in sub folders
I can also see that some of them are named differently causing some duplicate files.

Last time I downloaded it looked like this spookys.1..en.ny.klasskompis.f39bb75.svtplay
Now it looks like spookys.s02e01.1..en.ny.klasskompis.f39bb75.svtplay

I do seem to recall the filename changed maybe 6 months ago but now it seems to have changed back.
Can someone please assist with the config to get it into separate subfolders based on show.
 
Any help is greatly appreciated and my daughters will thank you for being able to watch their favorite shows this summer when we don't have internet.

### svtplay-dl versions:
svtplay-dl 4.0

### Operating system and Python version:
Windows 7, python 3.8

### What is the issue:

My config file:
```
default:
   path: E:\WEBrip
   subfolder: true
   all_episodes: true
   filename: "{title}.s{season}e{episode}.{episodename}.{id}.{service}.{ext}"
   subtitle: true
   merge_subtitle: true
service:
  svtplay:
    path: E:\WEBrip\svtplay
  urplay:
    path: E:\WEBrip\urplay
  tv4play:
    path: E:\WEBrip\tv4play
```
