### ISSUE TITLE
BUG: Downloads more files that asked for

### ISSUE THREAD

**Issue by ArneAnka** [spaam/svtplay-dl#1450]
### svtplay-dl versions:

svtplay-dl 4.9

### Operating system and Python version:

MacOS Monterey, 12.1
Python 2.7.18

### What is the issue:

Im using ~/.svtplay-dl.yaml with the following configuration

```
default:
  path: /Users/Adam/Movies/svtplay-dl

service:
  svtplay:
    path: /Users/Adam/Movies/svtplay-dl
    subtitle: true
    merge_subtitle: true
    all_episodes: true
    subfolder: true
    filename: "{title}.s{season}e{episode}.{episodename}-{service}.{ext}"
```

And if I try to download "hackad", with the following command `$ svtplay-dl https://www.svtplay.se/hackad` it downloads 21 files, 15 more that I would like it to do.

```
➜  ~ svtplay-dl https://www.svtplay.se/hackad
INFO: Episode 1 of 21
... snipp...
```

The 7th file is
```
Episode 7 of 21
INFO: Url: http://www.svtplay.se/nedslackt-land
```

And that seems to be "the following show"

https://i.imgur.com/1vB1EqE.png
