### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#328]
Im thinking about adding support for a config file for things.
- user / password for sites
- exclude
- http header? 
- stream priority
- preferred download method
- subtitles
- require subtitle

config format:
- json?
- yaml?
- xml?
- netrc?
- [ini](https://wiki.python.org/moin/ConfigParserExamples)?
- [jsonx](https://www-01.ibm.com/support/knowledgecenter/#!/SS9H2Y_7.1.0/com.ibm.dp.doc/json_jsonxconversionexample.html)?

**Comment by Sopor-** [comment]
ini :+1:

**Comment by dentarg** [comment]
ini sounds good to me

**Comment by spaam** [comment]
How about yaml format instead of ini? :D

**Comment by dentarg** [comment]
YAML sounds good to me :)

**Comment by spaam** [comment]
another question. should the command line argument override config or should the config file override command line? 
let say you have in `-q 2500` in command line  and in the config file you have `quality 3000` which one should we use? 2500, 3000 or should we hard fail when we have a conflict like this?

**Comment by dentarg** [comment]
I think it is most common that command line override config

**Comment by granbom** [comment]
I agree that command line should override config. And as I said the other week, would be nice to have sections that apply per domain, plus a default section (that per domain will override).

Understand that the config will not work like below day one. But I think it would be cool to have something similar eventually =)
```
default:
  preferred: hls
  subtitle: true
  path: ~/Videos/{site}/
  filename: {title}.s{season}e{episode}.{episode-name}.{id}.{ext}
eurosportplayer.com:
  user: jada
  psw: jada
  subtitle: false
dplay.se:
  user: hej
  psw: hopp
  quality: 3000
  flexible-quality: 200
  path: ~/Videos/{title}/
  filename: {title}.s{season}e{episode}.{episode-name}.{video.width}p.{ext}
```

And to complicate things even more =) have a "preset section" too....

```
presets:
   my-mobile:
       quality: 600
       flexible-quality: 100
       post-process: /usr/local/bin/ffmpeg -i {input} -c:v libx265 -crf 26 -c:a libopus -b:a 32k {output}
   whatevernameidliketohave:
      blablabla
```
`svtplay-dl --preset my-mobile <url>`

well, I guess 2.0.0 could be "a config file" and that command line overrides config =)
