### ISSUE TITLE
Issue with svtplay-dl.yaml (Config file)

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#934]
Hi, 

I got this issue when I try download from [svtplay.se](url) with help of a _**Config file**_ (svtplay-dl.yaml) with
 **svtplay-dl.exe** (version 2.0)

**URL:**
https://www.svtplay.se/video/16631590/kattfilmen
```
version: 2.0
DEBUG [1532889043.5266967] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.0
ERROR [1532889043.5427046] c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py/main: Your settings file(s) contain invalid YAML syntax! Please fix and restart!, while parsing a block mapping
  in "<unicode string>", line 6, column 5:
        path: /desktop/
        ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 10, column 22:
        filename: {title}.s{season}e{episode}.{episodenam ...

```

**Here Is my Config File**

```
default:
  path: ~/myown

service:
  svtplay:
    path: /desktop/
    exclude: Syntolkat,syntolkat,Teckentolkat,teckentolkat
    quality: 1000
    flexibleq: 500
    filename: {title}.s{season}e{episode}.{episodename}-{service}.{ext}

```

**Storage Directory for Config File** (svtplay-dl.yaml)
C:\Users\myown\AppData\Roaming\svtplay-dl\svtplay-dl.yaml
